name: test_workflow2 

on: push

jobs:
  jobs1:
    runs-on: ubuntu-latest
      
    name: UnitaryTests

  
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.11.5"
  
        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install pytest
            pip install requests
            pip install pandas
            pip install numpy
            pip install imbalanced-learn
            pip install lightgbm
  
        - name: Run tests
          run: pytest
  jobs2:
    needs: jobs1
    runs-on: ubuntu-latest

    steps: 
    - name: déploiement
      uses: actions/checkout@v3
      with: 
        url: https://ocprojet7-baw5gbumzhta75svyhtetq.streamlit.app/
        method: "POST"
